### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by pooraniravindhiran** [andreasgustavsson/find_moving_objects#1]
Can you please add an example and demo of this package, along with how to run it?

**Comment by pooraniravindhiran** [comment]
In addition, please explain on what will happen when there are static objects? Can this algorithm be used to distinguish static and dynamic objects in the same environment?

**Comment by andreasgustavsson** [comment]
Example is found here: https://github.com/andreasgustavsson/find_moving_objects_example
You find detailed information here: http://wiki.ros.org/find_moving_objects
In short, if you can determine your own velocity, then yes, you can use this package to distinguish between static and moving objects.
Yes, the information about the detected objects is given in several frames (see the wiki page for more information), including a fixed frame in which non-moving objects would have a velocity close to 0 m/s.
