### ISSUE TITLE
Roslaunch is not recognizing the package even after build

### ISSUE THREAD

**Issue by pooraniravindhiran** [andreasgustavsson/find_moving_objects#2]
A small error appeared when abs(unsigned int) was called in bank.cpp. I fixed the error and build the workspace. But, roslaunch is still not detecting it.

**Comment by turtleMaster20** [comment]
The same thing worked for me.

changed abs([#value]) to abs(int([#value])). I am using ROS Melodic

**Comment by dippatel1994** [comment]
@pooraniravi  and @turtleMaster20  can you post the steps you are taking to reproduce the error?

**Comment by dippatel1994** [comment]
> A small error appeared when abs(unsigned int) was called in bank.cpp. I fixed the error and build the workspace. But, roslaunch is still not detecting it.

@pooraniravi : After building your work space did you try sourcing bash file?

catkin_make && source devel/setup.bash 
echo "source devel/setup.bash" >> ~/.bashrc 

After that if you hit
"roslaunch find_moving_objects intel_realsense_d435_and_slamtec_rplidar_a2_w_enhancer.launch use_camera:=false use_bag:=true"

command than it will work. Please note that the documentation for this package usage is nearly zero. I want to use it to remove moving objects and keep static objects but I am not sure if this package will be useful or not. All the best!

**Comment by andreasgustavsson** [comment]
There is more detailed documentation on the usage here: http://wiki.ros.org/find_moving_objects

**Comment by turtleMaster20** [comment]
This issue can be closed. Like I said in the previous comment, the package is working well for me.

**Comment by dippatel1994** [comment]
@andreasgustavsson I want to track non-moving objects from lidar scan. Can you help me with that? I checked the wiki page but it is all about its argument. I will be grateful if you can share some more detail about this package.

**Comment by andreasgustavsson** [comment]
@dippatel1994 This package does not track any objects per se. Instead, it gives you a continuous stream of information (i.e., messages) on detected objects. The wiki page, section 1.1, explains this. The information about the found objects is given in several frames, including a fixed frame which could be used to detect non-moving objects (the non-moving objects would have a velocity close to 0 m/s in this frame).
You could "easily" build a package on top of this package that uses the information provided by this package to track the found objects. Unfortunately, I do not currently have the time or resources to create such a package.
It sounds to me like you are probably trying to create a map of the environment, containing non-moving objects while moving objects should be discarded. Is this assumption fairly true? In that case, you could also explore other ROS packages explicitly created for mapping purposes.

**Comment by andreasgustavsson** [comment]
Closing this issue based on the comment from turtleMaster20.
