### ISSUE TITLE
While robot is moving and above ground plane ,It is detecting static objects as moving objects ,how can i solve this issue ?

### ISSUE THREAD

**Issue by mefrankli** [andreasgustavsson/find_moving_objects#3]
Hi, I'm using this pkg with a simulated drone, When the drone is on the ground plane and in idle condition this pkg works perfectly, but after takeoff, due to the robot motion it is detecting every object as static, I have tried reducing the speed of the drone and still not working.is there is any way /suggestion to make it working ?

**Comment by kwnstantinageras** [comment]
@mefrankli  did you find any solution to this? I am thinking of using this package as well.

**Comment by andreasgustavsson** [comment]
I apologize for the late response - I hope you already found a solution. Like you found out, this package was mainly designed for ground-based operation. Any contribution aiming at improving it also for flight-based operation is welcome.
